/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.credits.client.node.thrift;


import com.credits.general.thrift.generate.Variant;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-10-16")
public class SmartContractInvocation implements org.apache.thrift.TBase<SmartContractInvocation, SmartContractInvocation._Fields>, java.io.Serializable, Cloneable, Comparable<SmartContractInvocation> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SmartContractInvocation");

  private static final org.apache.thrift.protocol.TField SOURCE_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("sourceCode", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField BYTE_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("byteCode", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField HASH_STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("hashState", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField METHOD_FIELD_DESC = new org.apache.thrift.protocol.TField("method", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField PARAMS_FIELD_DESC = new org.apache.thrift.protocol.TField("params", org.apache.thrift.protocol.TType.LIST, (short)5);
  private static final org.apache.thrift.protocol.TField FORGET_NEW_STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("forgetNewState", org.apache.thrift.protocol.TType.BOOL, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SmartContractInvocationStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SmartContractInvocationTupleSchemeFactory();

  public java.lang.String sourceCode; // required
  public java.nio.ByteBuffer byteCode; // required
  public java.lang.String hashState; // required
  public java.lang.String method; // required
  public java.util.List<Variant> params; // required
  public boolean forgetNewState; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SOURCE_CODE((short)1, "sourceCode"),
    BYTE_CODE((short)2, "byteCode"),
    HASH_STATE((short)3, "hashState"),
    METHOD((short)4, "method"),
    PARAMS((short)5, "params"),
    FORGET_NEW_STATE((short)6, "forgetNewState");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SOURCE_CODE
          return SOURCE_CODE;
        case 2: // BYTE_CODE
          return BYTE_CODE;
        case 3: // HASH_STATE
          return HASH_STATE;
        case 4: // METHOD
          return METHOD;
        case 5: // PARAMS
          return PARAMS;
        case 6: // FORGET_NEW_STATE
          return FORGET_NEW_STATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __FORGETNEWSTATE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SOURCE_CODE, new org.apache.thrift.meta_data.FieldMetaData("sourceCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BYTE_CODE, new org.apache.thrift.meta_data.FieldMetaData("byteCode", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.HASH_STATE, new org.apache.thrift.meta_data.FieldMetaData("hashState", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.METHOD, new org.apache.thrift.meta_data.FieldMetaData("method", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PARAMS, new org.apache.thrift.meta_data.FieldMetaData("params", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Variant.class))));
    tmpMap.put(_Fields.FORGET_NEW_STATE, new org.apache.thrift.meta_data.FieldMetaData("forgetNewState", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SmartContractInvocation.class, metaDataMap);
  }

  public SmartContractInvocation() {
  }

  public SmartContractInvocation(
    java.lang.String sourceCode,
    java.nio.ByteBuffer byteCode,
    java.lang.String hashState,
    java.lang.String method,
    java.util.List<Variant> params,
    boolean forgetNewState)
  {
    this();
    this.sourceCode = sourceCode;
    this.byteCode = org.apache.thrift.TBaseHelper.copyBinary(byteCode);
    this.hashState = hashState;
    this.method = method;
    this.params = params;
    this.forgetNewState = forgetNewState;
    setForgetNewStateIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SmartContractInvocation(SmartContractInvocation other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetSourceCode()) {
      this.sourceCode = other.sourceCode;
    }
    if (other.isSetByteCode()) {
      this.byteCode = org.apache.thrift.TBaseHelper.copyBinary(other.byteCode);
    }
    if (other.isSetHashState()) {
      this.hashState = other.hashState;
    }
    if (other.isSetMethod()) {
      this.method = other.method;
    }
    if (other.isSetParams()) {
      java.util.List<Variant> __this__params = new java.util.ArrayList<Variant>(other.params.size());
      for (Variant other_element : other.params) {
        __this__params.add(new Variant(other_element));
      }
      this.params = __this__params;
    }
    this.forgetNewState = other.forgetNewState;
  }

  public SmartContractInvocation deepCopy() {
    return new SmartContractInvocation(this);
  }

  @Override
  public void clear() {
    this.sourceCode = null;
    this.byteCode = null;
    this.hashState = null;
    this.method = null;
    this.params = null;
    setForgetNewStateIsSet(false);
    this.forgetNewState = false;
  }

  public java.lang.String getSourceCode() {
    return this.sourceCode;
  }

  public SmartContractInvocation setSourceCode(java.lang.String sourceCode) {
    this.sourceCode = sourceCode;
    return this;
  }

  public void unsetSourceCode() {
    this.sourceCode = null;
  }

  /** Returns true if field sourceCode is set (has been assigned a value) and false otherwise */
  public boolean isSetSourceCode() {
    return this.sourceCode != null;
  }

  public void setSourceCodeIsSet(boolean value) {
    if (!value) {
      this.sourceCode = null;
    }
  }

  public byte[] getByteCode() {
    setByteCode(org.apache.thrift.TBaseHelper.rightSize(byteCode));
    return byteCode == null ? null : byteCode.array();
  }

  public java.nio.ByteBuffer bufferForByteCode() {
    return org.apache.thrift.TBaseHelper.copyBinary(byteCode);
  }

  public SmartContractInvocation setByteCode(byte[] byteCode) {
    this.byteCode = byteCode == null ? (java.nio.ByteBuffer)null : java.nio.ByteBuffer.wrap(byteCode.clone());
    return this;
  }

  public SmartContractInvocation setByteCode(java.nio.ByteBuffer byteCode) {
    this.byteCode = org.apache.thrift.TBaseHelper.copyBinary(byteCode);
    return this;
  }

  public void unsetByteCode() {
    this.byteCode = null;
  }

  /** Returns true if field byteCode is set (has been assigned a value) and false otherwise */
  public boolean isSetByteCode() {
    return this.byteCode != null;
  }

  public void setByteCodeIsSet(boolean value) {
    if (!value) {
      this.byteCode = null;
    }
  }

  public java.lang.String getHashState() {
    return this.hashState;
  }

  public SmartContractInvocation setHashState(java.lang.String hashState) {
    this.hashState = hashState;
    return this;
  }

  public void unsetHashState() {
    this.hashState = null;
  }

  /** Returns true if field hashState is set (has been assigned a value) and false otherwise */
  public boolean isSetHashState() {
    return this.hashState != null;
  }

  public void setHashStateIsSet(boolean value) {
    if (!value) {
      this.hashState = null;
    }
  }

  public java.lang.String getMethod() {
    return this.method;
  }

  public SmartContractInvocation setMethod(java.lang.String method) {
    this.method = method;
    return this;
  }

  public void unsetMethod() {
    this.method = null;
  }

  /** Returns true if field method is set (has been assigned a value) and false otherwise */
  public boolean isSetMethod() {
    return this.method != null;
  }

  public void setMethodIsSet(boolean value) {
    if (!value) {
      this.method = null;
    }
  }

  public int getParamsSize() {
    return (this.params == null) ? 0 : this.params.size();
  }

  public java.util.Iterator<Variant> getParamsIterator() {
    return (this.params == null) ? null : this.params.iterator();
  }

  public void addToParams(Variant elem) {
    if (this.params == null) {
      this.params = new java.util.ArrayList<Variant>();
    }
    this.params.add(elem);
  }

  public java.util.List<Variant> getParams() {
    return this.params;
  }

  public SmartContractInvocation setParams(java.util.List<Variant> params) {
    this.params = params;
    return this;
  }

  public void unsetParams() {
    this.params = null;
  }

  /** Returns true if field params is set (has been assigned a value) and false otherwise */
  public boolean isSetParams() {
    return this.params != null;
  }

  public void setParamsIsSet(boolean value) {
    if (!value) {
      this.params = null;
    }
  }

  public boolean isForgetNewState() {
    return this.forgetNewState;
  }

  public SmartContractInvocation setForgetNewState(boolean forgetNewState) {
    this.forgetNewState = forgetNewState;
    setForgetNewStateIsSet(true);
    return this;
  }

  public void unsetForgetNewState() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FORGETNEWSTATE_ISSET_ID);
  }

  /** Returns true if field forgetNewState is set (has been assigned a value) and false otherwise */
  public boolean isSetForgetNewState() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FORGETNEWSTATE_ISSET_ID);
  }

  public void setForgetNewStateIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FORGETNEWSTATE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case SOURCE_CODE:
      if (value == null) {
        unsetSourceCode();
      } else {
        setSourceCode((java.lang.String)value);
      }
      break;

    case BYTE_CODE:
      if (value == null) {
        unsetByteCode();
      } else {
        if (value instanceof byte[]) {
          setByteCode((byte[])value);
        } else {
          setByteCode((java.nio.ByteBuffer)value);
        }
      }
      break;

    case HASH_STATE:
      if (value == null) {
        unsetHashState();
      } else {
        setHashState((java.lang.String)value);
      }
      break;

    case METHOD:
      if (value == null) {
        unsetMethod();
      } else {
        setMethod((java.lang.String)value);
      }
      break;

    case PARAMS:
      if (value == null) {
        unsetParams();
      } else {
        setParams((java.util.List<Variant>)value);
      }
      break;

    case FORGET_NEW_STATE:
      if (value == null) {
        unsetForgetNewState();
      } else {
        setForgetNewState((java.lang.Boolean)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SOURCE_CODE:
      return getSourceCode();

    case BYTE_CODE:
      return getByteCode();

    case HASH_STATE:
      return getHashState();

    case METHOD:
      return getMethod();

    case PARAMS:
      return getParams();

    case FORGET_NEW_STATE:
      return isForgetNewState();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SOURCE_CODE:
      return isSetSourceCode();
    case BYTE_CODE:
      return isSetByteCode();
    case HASH_STATE:
      return isSetHashState();
    case METHOD:
      return isSetMethod();
    case PARAMS:
      return isSetParams();
    case FORGET_NEW_STATE:
      return isSetForgetNewState();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SmartContractInvocation)
      return this.equals((SmartContractInvocation)that);
    return false;
  }

  public boolean equals(SmartContractInvocation that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_sourceCode = true && this.isSetSourceCode();
    boolean that_present_sourceCode = true && that.isSetSourceCode();
    if (this_present_sourceCode || that_present_sourceCode) {
      if (!(this_present_sourceCode && that_present_sourceCode))
        return false;
      if (!this.sourceCode.equals(that.sourceCode))
        return false;
    }

    boolean this_present_byteCode = true && this.isSetByteCode();
    boolean that_present_byteCode = true && that.isSetByteCode();
    if (this_present_byteCode || that_present_byteCode) {
      if (!(this_present_byteCode && that_present_byteCode))
        return false;
      if (!this.byteCode.equals(that.byteCode))
        return false;
    }

    boolean this_present_hashState = true && this.isSetHashState();
    boolean that_present_hashState = true && that.isSetHashState();
    if (this_present_hashState || that_present_hashState) {
      if (!(this_present_hashState && that_present_hashState))
        return false;
      if (!this.hashState.equals(that.hashState))
        return false;
    }

    boolean this_present_method = true && this.isSetMethod();
    boolean that_present_method = true && that.isSetMethod();
    if (this_present_method || that_present_method) {
      if (!(this_present_method && that_present_method))
        return false;
      if (!this.method.equals(that.method))
        return false;
    }

    boolean this_present_params = true && this.isSetParams();
    boolean that_present_params = true && that.isSetParams();
    if (this_present_params || that_present_params) {
      if (!(this_present_params && that_present_params))
        return false;
      if (!this.params.equals(that.params))
        return false;
    }

    boolean this_present_forgetNewState = true;
    boolean that_present_forgetNewState = true;
    if (this_present_forgetNewState || that_present_forgetNewState) {
      if (!(this_present_forgetNewState && that_present_forgetNewState))
        return false;
      if (this.forgetNewState != that.forgetNewState)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetSourceCode()) ? 131071 : 524287);
    if (isSetSourceCode())
      hashCode = hashCode * 8191 + sourceCode.hashCode();

    hashCode = hashCode * 8191 + ((isSetByteCode()) ? 131071 : 524287);
    if (isSetByteCode())
      hashCode = hashCode * 8191 + byteCode.hashCode();

    hashCode = hashCode * 8191 + ((isSetHashState()) ? 131071 : 524287);
    if (isSetHashState())
      hashCode = hashCode * 8191 + hashState.hashCode();

    hashCode = hashCode * 8191 + ((isSetMethod()) ? 131071 : 524287);
    if (isSetMethod())
      hashCode = hashCode * 8191 + method.hashCode();

    hashCode = hashCode * 8191 + ((isSetParams()) ? 131071 : 524287);
    if (isSetParams())
      hashCode = hashCode * 8191 + params.hashCode();

    hashCode = hashCode * 8191 + ((forgetNewState) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(SmartContractInvocation other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetSourceCode()).compareTo(other.isSetSourceCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSourceCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sourceCode, other.sourceCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetByteCode()).compareTo(other.isSetByteCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetByteCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.byteCode, other.byteCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetHashState()).compareTo(other.isSetHashState());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHashState()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hashState, other.hashState);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetMethod()).compareTo(other.isSetMethod());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMethod()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.method, other.method);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetParams()).compareTo(other.isSetParams());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetParams()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.params, other.params);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetForgetNewState()).compareTo(other.isSetForgetNewState());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetForgetNewState()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.forgetNewState, other.forgetNewState);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SmartContractInvocation(");
    boolean first = true;

    sb.append("sourceCode:");
    if (this.sourceCode == null) {
      sb.append("null");
    } else {
      sb.append(this.sourceCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("byteCode:");
    if (this.byteCode == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.byteCode, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("hashState:");
    if (this.hashState == null) {
      sb.append("null");
    } else {
      sb.append(this.hashState);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("method:");
    if (this.method == null) {
      sb.append("null");
    } else {
      sb.append(this.method);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("params:");
    if (this.params == null) {
      sb.append("null");
    } else {
      sb.append(this.params);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("forgetNewState:");
    sb.append(this.forgetNewState);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SmartContractInvocationStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SmartContractInvocationStandardScheme getScheme() {
      return new SmartContractInvocationStandardScheme();
    }
  }

  private static class SmartContractInvocationStandardScheme extends org.apache.thrift.scheme.StandardScheme<SmartContractInvocation> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SmartContractInvocation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SOURCE_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sourceCode = iprot.readString();
              struct.setSourceCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BYTE_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.byteCode = iprot.readBinary();
              struct.setByteCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // HASH_STATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.hashState = iprot.readString();
              struct.setHashStateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // METHOD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.method = iprot.readString();
              struct.setMethodIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // PARAMS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.params = new java.util.ArrayList<Variant>(_list0.size);
                Variant _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new Variant();
                  _elem1.read(iprot);
                  struct.params.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setParamsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // FORGET_NEW_STATE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.forgetNewState = iprot.readBool();
              struct.setForgetNewStateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SmartContractInvocation struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.sourceCode != null) {
        oprot.writeFieldBegin(SOURCE_CODE_FIELD_DESC);
        oprot.writeString(struct.sourceCode);
        oprot.writeFieldEnd();
      }
      if (struct.byteCode != null) {
        oprot.writeFieldBegin(BYTE_CODE_FIELD_DESC);
        oprot.writeBinary(struct.byteCode);
        oprot.writeFieldEnd();
      }
      if (struct.hashState != null) {
        oprot.writeFieldBegin(HASH_STATE_FIELD_DESC);
        oprot.writeString(struct.hashState);
        oprot.writeFieldEnd();
      }
      if (struct.method != null) {
        oprot.writeFieldBegin(METHOD_FIELD_DESC);
        oprot.writeString(struct.method);
        oprot.writeFieldEnd();
      }
      if (struct.params != null) {
        oprot.writeFieldBegin(PARAMS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.params.size()));
          for (Variant _iter3 : struct.params)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(FORGET_NEW_STATE_FIELD_DESC);
      oprot.writeBool(struct.forgetNewState);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SmartContractInvocationTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SmartContractInvocationTupleScheme getScheme() {
      return new SmartContractInvocationTupleScheme();
    }
  }

  private static class SmartContractInvocationTupleScheme extends org.apache.thrift.scheme.TupleScheme<SmartContractInvocation> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SmartContractInvocation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSourceCode()) {
        optionals.set(0);
      }
      if (struct.isSetByteCode()) {
        optionals.set(1);
      }
      if (struct.isSetHashState()) {
        optionals.set(2);
      }
      if (struct.isSetMethod()) {
        optionals.set(3);
      }
      if (struct.isSetParams()) {
        optionals.set(4);
      }
      if (struct.isSetForgetNewState()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetSourceCode()) {
        oprot.writeString(struct.sourceCode);
      }
      if (struct.isSetByteCode()) {
        oprot.writeBinary(struct.byteCode);
      }
      if (struct.isSetHashState()) {
        oprot.writeString(struct.hashState);
      }
      if (struct.isSetMethod()) {
        oprot.writeString(struct.method);
      }
      if (struct.isSetParams()) {
        {
          oprot.writeI32(struct.params.size());
          for (Variant _iter4 : struct.params)
          {
            _iter4.write(oprot);
          }
        }
      }
      if (struct.isSetForgetNewState()) {
        oprot.writeBool(struct.forgetNewState);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SmartContractInvocation struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.sourceCode = iprot.readString();
        struct.setSourceCodeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.byteCode = iprot.readBinary();
        struct.setByteCodeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.hashState = iprot.readString();
        struct.setHashStateIsSet(true);
      }
      if (incoming.get(3)) {
        struct.method = iprot.readString();
        struct.setMethodIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.params = new java.util.ArrayList<Variant>(_list5.size);
          Variant _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new Variant();
            _elem6.read(iprot);
            struct.params.add(_elem6);
          }
        }
        struct.setParamsIsSet(true);
      }
      if (incoming.get(5)) {
        struct.forgetNewState = iprot.readBool();
        struct.setForgetNewStateIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

